language: ruby

sudo: false

cache:
  - apt
  - bundler

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.0

addons:
  apt:
    packages:
      - graphviz

matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.4.1.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.4.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.4.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.4.2.x
  allow_failures:
    - rvm: ruby-head
